project:
  type: website
  output-dir: docs

website:
  title: "Ioan Scheffel"
  navbar:
    left:
      - href: index.qmd
        text: about
      - href: publications.qmd
        text: publications
      - href: talks.qmd
        text: talks
      - href: cv.qmd
        text: cv

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
